services:

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

  tc-web:
    build:
      context: ./tc-web
      dockerfile: Dockerfile
      target: dev
    ports:
      - ${TC_WEB_PORT}:${TC_WEB_PORT}
    environment:
      API_URL: http://tc-api:${TC_API_PORT}
      HOSTNAME: 0.0.0.0
      PORT: ${TC_WEB_PORT}
    volumes:
      - ./tc-web:/app
    depends_on:
      - tc-api

  tc-api:
    build:
      context: ./tc-api
      dockerfile: Dockerfile
      target: dev
    ports:
      - '${TC_API_PORT}:${TC_API_PORT}'
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}      
      NODE_ENV: ${NODE_ENV}
      AWS_REGION: ${AWS_REGION}
      JWT_SECRET: ${JWT_SECRET}
      LAMBDA_RENDER_NAME: ${LAMBDA_RENDER_NAME} 
    volumes:
      - ./tc-api:/app
    depends_on:
      - postgres
 
volumes:
  pgdata:
